### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by Tobaloidee** [coffeepostal/beer-tracker#1]
Hi @coffeepostal  Good day! I am a graphic artist and would like to contribute & design a logo for your project. If you are interested and would allow me, I will begin asap.   - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by coffeepostal** [comment]
Hello @Tobaloidee, thanks for offering to contribute. At the moment, this is just an exercise for me to learn full stack development, and I don't intend on pushing it into production, but, if I do, I'll definitely be in touch. Thanks!

**Comment by Tobaloidee** [comment]
Thanks for your feedback Sir..best regards!
